# Generated by Django 5.2.12 on 2026-03-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('time_text', models.CharField(max_length=200)),
                ('bringing', models.CharField(blank=True, max_length=200)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('tag', models.CharField(max_length=50)),
                ('voter_name', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('day', 'tag', 'voter_name')},
            },
        ),
    ]
